name: Deploy
on:
  push:
    tags:
      - rc-*
      
jobs:

  check:
    uses: ./.github/workflows/main.yml

  release-build:
    runs-on: ubuntu-latest
    needs: check

    steps:
      - name: Getting release tag
        run:
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}

