name: Deploy
on:
  push:
    tags:
      - rc-*
      
jobs:

#  check:
#    uses: ./.github/workflows/main.yml

  release-build:
    runs-on: ubuntu-latest
#    needs: check

    steps:
      - name: Getting release tag
        run: |
          echo ${{ github.ref_name }}
          git describe --abbrev=0 --tags ${currentTag}^

