name: Deploy
on:
  push:
    tags:
      - rc-*
      
jobs:

#  check:
#    uses: ./.github/workflows/main.yml

  release-build:
    runs-on: ubuntu-latest
#    needs: check

    steps:

      - name: Setup checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Getting release tag
        run: |
          prevTag = git describe --abbrev=0 --tags ${{ github.ref_name }}^ 
          currentTag = ${{ github.ref_name }}
          
          tagsArr = "$prevTag"
          tagsArr += ".."
          tagsArr += "$currentTag"
          
          echo tagsArr


