name: Deploy
on:
  push:
    tags:
      - rc-*
      
jobs:

#  check:
#    uses: ./.github/workflows/main.yml

  release-build:
    runs-on: ubuntu-latest
#    needs: check

    steps:

      - name: Setup checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Getting pre tag
        run: echo "PREV_TAG=$(echo $(git describe --abbrev=0 --tags ${{ github.ref_name }}^))" >> $GITHUB_ENV
      - name: Getting commits
        run: echo "COMMITS=$(echo [$(git log --pretty=format:"[%h,%an,%s]" ${{env.PREV_TAG}}..${{ github.ref_name }})])" >> $GITHUB_ENV
      - name: get
        run: echo $COMMITS
#          prevTag = git describe --abbrev=0 --tags ${{ github.ref_name }}^
#          currentTag = ${{ github.ref_name }}
#
#          tagsArr = "$prevTag"
#          tagsArr += ".."
#          tagsArr += "$currentTag"
#
#          echo tagsArr


