name: CI on push

on:
  push:
    branches:
      - '**'
    workflow_call:

jobs:
  TS-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: 16.16.0
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
      - name: TS check
        run: npm run ts
      - name: Linter check
        run: npm run lint


