name: CI on push

on:
  push:
    branches:
      - '**'
    workflow_call:

jobs:
  app-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 16.16.0
        uses: actions/setup-node@v1
        with:
          node-version: 16.16.0
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
      - name: TS check
        run: npm run ts
      - name: Linter check
        run: npm run lint


